version = 0.1

[default.deploy.parameters]
stack_name = "leavemanagementapi-stack"
resolve_s3 = true
s3_prefix = "leavemanagementapi-stack"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "LeaveRequestsTableNameParam=\"LeaveRequestsTableProd\" ExternalDependencies=\"@aws-sdk/* jsonwebtoken uuid\""
image_repositories = []
