openapi: 3.0.1
info:
  title: LeaveManagementApi
  version: '1.0'

paths:
  /leaves:
    post:
      summary: Submit a new leave request
      x-amazon-apigateway-integration:
        httpMethod: POST
        uri: arn:aws:apigateway:ap-south-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-south-1:043309342820:function:leavemanagementapi-stack-ApplyLeaveFunction/invocations
        passthroughBehavior: when_no_match
        type: aws_proxy
      security:
        - CustomJwtAuthorizer: []
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Leave request submitted successfully
        '400':
          description: Invalid request
        '500':
          description: Internal server error

  /leaves/{requestId}/approve:
    get:
      summary: Approve a leave request
      x-amazon-apigateway-integration:
        httpMethod: GET
        uri: arn:aws:apigateway:ap-south-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-south-1:043309342820:function:leavemanagementapi-stack-ProcessApprovalFunction/invocations
        passthroughBehavior: when_no_match
        type: aws_proxy
      parameters:
        - in: path
          name: requestId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Leave request approved
        '404':
          description: Request ID not found

  /leaves/{requestId}/reject:
    get:
      summary: Reject a leave request
      x-amazon-apigateway-integration:
        httpMethod: GET
        uri: arn:aws:apigateway:ap-south-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-south-1:123456789012:function:leavemanagementapi-stack-ProcessApprovalFunction/invocations
        passthroughBehavior: when_no_match
        type: aws_proxy
      parameters:
        - in: path
          name: requestId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Leave request rejected
        '404':
          description: Request ID not found

components:
  securitySchemes:
    CustomJwtAuthorizer:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: custom
      x-amazon-apigateway-authorizer:
        type: token
        identitySource: method.request.header.Authorization
        authorizerUri: arn:aws:apigateway:ap-south-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-south-1:043309342820:function:leavemanagementapi-stack-CustomAuthorizerLambda/invocations
        authorizerResultTtlInSeconds: 300
